FROM node:18.9-alpine

RUN npm install -g pnpm

ENV NODE_ENV development

WORKDIR /usr/src/app

COPY package*.json pnpm-lock.yaml* ./

RUN pnpm i

COPY . .

EXPOSE 5050

EXPOSE 24678

CMD pnpm run dev